server:
    port: 10000
    
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 150
      connectionTimeout: 3000